name: fanwaave_flutter
description: Flutter client for Fanwaave
publish_to: "none"
version: 0.1.0
environment:
  sdk: ">=3.5.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  ores_dnd:
    git:
      url: https://github.com/ORESoftware/ores-dnd.git
      ref: 0b96c5eac6cbb210e29249ce30509c792b7e8703
      path: src/dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
